name: coinvault_flutter
version: 1.0.0+1
description: CoinVault mobile app — earn coins via tasks, offers, surveys, spin & scratch cards. Flutter frontend for the CoinVault backend API.
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  firebase_database: ^10.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.jpg
    - assets/app_icon_name.png
    - assets/wheel.png
    - assets/spin_bg.png
    - assets/coin.png
    - assets/scratch.png
    - assets/trophy.png
    - assets/logos/
