org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.installations.paths=/usr/lib/jvm/java-17-openjdk-arm64
android.aapt2FromMavenOverride=/usr/lib/android-sdk/build-tools/29.0.3/aapt2
android.cmake.dir=/root/android-sdk/ndk/26.3.11579264/build/cmake
android.cmake.options=-DCMAKE_POLICY_VERSION_MINIMUM=3.10
